### PR TITLE
Initial import of vespa exporter

### PR DESCRIPTION
**Pull request by ghost**
This is the code we have running in stage to export metrics from Vespa into Prometheus.

### CODE REVIEW

**Comment by bratseth** [comment]
Ping CLA checker.

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by bratseth** [comment]
@zoyvind could you sign the CLA please?

**Comment by ghost** [comment]
I have signed the CLA.

**Comment by bratseth** [comment]
LGTM - merging.
Arne, please have a look at it too when you have a chance.

**Pull request merged**
